# Author:  PH01L
# Email:   phoil@osrsbox.com
# Website: https://www.osrsbox.com
#
# Description:
# Dockerfile for osrsbox-api
#
# Copyright (c) 2020, PH01L
# 
###############################################################################
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################
version: '3'
services:
  eve:
    build:
      context: eve
      dockerfile: Dockerfile
    container_name: osrsbox-api-eve
    image: python:3.7-slim-buster
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGO_URI: "mongodb://mongo/db"
      MONGO_PORT: 27017
      MONGO_USERNAME: someusername
      MONGO_PASSWORD: somepassword
    volumes:
      - evedata:/var/www
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    container_name: osrsbox-api-mongo
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: osrsbox-db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongo/create-database.js:/docker-entrypoint-initdb.d/create-database.js:ro
      - mongodata:/data/db
    networks:
      - backend

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: osrsbox-api-nginx
    image: nginx:latest
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "false"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/:/etc/nginx/certs/
      - nginxdata:/var/log/nginx
    depends_on:
      - eve
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodata:
    driver: local
  evedata:
    driver: local
  nginxdata:
    driver: local
